version: "3.8"
services:

    web-service:
        build:
            context: .
            dockerfile: web-service/Dockerfile
        environment:
            GLOSSARY_HOST: glossary-service
        image: web-service
        networks:
            - microservices
        ports:
            - 8000:8000

    glossary-service:
        build:
            context: .
            dockerfile: glossary-service/Dockerfile
        image: glossary-service
        networks:
            - microservices

networks:
    microservices:

